apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-devops-component
  description: azure devops component
  annotations:
    # GitHub Plugin Annotations
    flowsource/github-repo-owner: maniksakhuja
    flowsource/github-repo-name: App1
    flowsource/azure-devops-project-key: 'Onboarding'
    flowsource/durationInDays: '120'
spec:
  type: service # website or service
  owner: user:guest
  lifecycle: experimental
